# Import Libraries

In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Data visualization 
import matplotlib.pyplot as plt
import seaborn as sns

# Data Load

In [2]:
import pandas as pd

# File path
file_path = r"C:\Users\Admin\Desktop\Project\Data\BankChurners.csv"

# Load the dataset
df = pd.read_csv(file_path)

# Visualization
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

# Drop columns

In [3]:
# Dropping Naive Bayes output columns 
df.drop(
    columns=[
        'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
        'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'
    ],
    inplace=True
)

# Info

In [4]:
df.columns = (df.columns.str.strip())

print("Dataset Info:")
df.info()

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CLIENTNUM                 10127 non-null  int64
 1   Attrition_Flag            10127 non-null  object
 2   Customer_Age              10127 non-null  int64
 3   Gender                    10127 non-null  object
 4   Dependent_count           10127 non-null  int64
 5   Education_Level           10127 non-null  object
 6   Marital_Status            10127 non-null  object
 7   Income_Category           10127 non-null  object
 8   Card_Category             10127 non-null  object
 9   Months_on_book            10127 non-null  int64
 10  Total_Relationship_Count  10127 non-null  int64
 11  Months_Inactive_12_mon    10127 non-null  int64
 12  Contacts_Count_12_mon     10127 non-null  int64
 13  Credit_Limit              10127 non-null  float64
 14  Total_Revolving_Bal       10127 non-null  int64
 15  Avg_Open_To_Buy           10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1      10127 non-null  float64
 17  Total_Trans_Amt           10127 non-null  int64
 18  Total_Trans_Ct            10127 non-null  int64
 19  Total_Ct_Chng_Q4_Q1       10127 non-null  float64
 20  Avg_Utilization_Ratio     10127 non-null  float64
dtypes: float64(5), int64(10), object(6)
memory usage: 1.6+ MB

# Nulls and Duplicates

In [5]:
print(df.isna().sum())
print("Number of duplicated rows:", df.duplicated().sum())

CLIENTNUM                   0
Attrition_Flag              0
Customer_Age                0
Gender                      0
Dependent_count             0
Education_Level             0
Marital_Status              0
Income_Category             0
Card_Category               0
Months_on_book              0
Total_Relationship_Count    0
Months_Inactive_12_mon      0
Contacts_Count_12_mon       0
Credit_Limit                0
Total_Revolving_Bal         0
Avg_Open_To_Buy             0
Total_Amt_Chng_Q4_Q1        0
Total_Trans_Amt             0
Total_Trans_Ct              0
Total_Ct_Chng_Q4_Q1         0
Avg_Utilization_Ratio       0
dtype: int64
Number of duplicated rows: 0

In [6]:
num_features = []

for col in df.columns:
    if df[col].dtype in ['int64', 'float64']:
        num_features.append(col)

cat_features = []
for col in df.columns:
    if df[col].dtype in ['object','str']:
        cat_features.append(col)

print("-"*140)
print("Numerical Features:", num_features)
print("-"*140)
print("Categorical Features:", cat_features)

--------------------------------------------------------------------------------------------------------------------------------------------
Numerical Features: ['CLIENTNUM', 'Customer_Age', 'Dependent_count', 'Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon', 'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal', 'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt', 'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio']
--------------------------------------------------------------------------------------------------------------------------------------------
Categorical Features: ['Attrition_Flag', 'Gender', 'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category']

In [7]:
summary = df[cat_features].describe().T
summary["unique_values"] = df[cat_features].apply(
    lambda col: col.unique().tolist()
)
summary["Unknown_Count"] = df[cat_features].apply(
    lambda col: (col == 'Unknown').sum()
)
summary

,count,unique,top,freq,unique_values,Unknown_Count
Attrition_Flag,10127,2,Existing Customer,8500,"[Existing Customer, Attrited Customer]",0
Gender,10127,2,F,5358,"[M, F]",0
Education_Level,10127,7,Graduate,3128,"[High School, Graduate, Uneducated, Unknown, C...",1519
Marital_Status,10127,4,Married,4687,"[Married, Single, Unknown, Divorced]",749
Income_Category,10127,6,Less than $40K,3561,"[$60K - $80K, Less than $40K, $80K - $120K, $4...",1112
Card_Category,10127,4,Blue,9436,"[Blue, Gold, Silver, Platinum]",0

In [8]:
cols = ['Income_Category', 'Education_Level', 'Marital_Status']

unknown_counts = {c: (df[c] == 'Unknown').sum() for c in cols}
unknown_counts

{'Income_Category': np.int64(1112),
 'Education_Level': np.int64(1519),
 'Marital_Status': np.int64(749)}

In [9]:
df['unknown_count'] = sum((df[c] == 'Unknown').astype(int) for c in cols)

df['unknown_count'].value_counts().sort_index()

unknown_count
0    7081
1    2719
2     320
3       7
Name: count, dtype: int64

In [10]:
pd.crosstab(
    df['unknown_count'],
    df['Attrition_Flag'],
    normalize='index'
)

Attrition_Flag  Attrited Customer  Existing Customer
unknown_count
0                        0.157181           0.842819
1                        0.168076           0.831924
2                        0.175000           0.825000
3                        0.142857           0.857143

In [11]:

df[cols] = df[cols].replace('Unknown', 'Not_Provided')

# Dictionary

- **CLIENTNUM** → Unique customer identifier (ID)

- **Attrition_Flag** → Indicates whether the customer is active (Existing Customer) or has churned (Attrited Customer)

- **Customer_Age** → Customer age (in years)

- **Gender** → Customer gender (M or F)

- **Dependent_count** → Number of dependents of the customer

- **Education_Level** → Customer’s education level

- **Marital_Status** → Customer’s marital status

- **Income_Category** → Customer’s annual income range

- **Card_Category** → Customer’s credit card category (Blue, Silver, Gold, Platinum)

- **Months_on_book** → Length of the customer relationship with the bank (in months)

- **Total_Relationship_Count** → Total number of products the customer has with the bank

- **Months_Inactive_12_mon** → Number of inactive months in the last 12 months

- **Contacts_Count_12_mon** → Number of contacts between the customer and the bank in the last 12 months

- **Credit_Limit** → Customer’s total credit limit

- **Total_Revolving_Bal** → Total revolving balance on the credit card

- **Avg_Open_To_Buy** → Average available credit for use

- **Total_Trans_Amt** → Total transaction amount in the last 12 months

- **Total_Trans_Ct** → Total number of transactions in the last 12 months

- **Total_Amt_Chng_Q4_Q1** → Percentage change in transaction amount from Q1 to Q4

- **Total_Ct_Chng_Q4_Q1** → Percentage change in transaction count from Q1 to Q4

- **Avg_Utilization_Ratio** → Average credit utilization ratio

# Save DF

In [12]:
import os

# Path to the folder where the file will be saved
folder_path = r"C:\Users\Admin\Desktop\Project\Data"

# Cleaned dataset file name
file_name = "bank_churn_cleaned.csv"

# Create full file path
full_path = os.path.join(folder_path, file_name)

# Save the cleaned DataFrame to CSV
df.to_csv(full_path, index=False, encoding='utf-8-sig')

print(f"Cleaned dataset saved successfully at: {full_path}")

Cleaned dataset saved successfully at: C:\Users\Admin\Desktop\Project\Data\bank_churn_cleaned.csv